(in-package :lem-user)

(define-color-theme "abap" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#ff0000" :background "#ffffff")
  (syntax-string-attribute :foreground "#5faf00" :background "#ffffff")
  (syntax-comment-attribute :foreground "#878787" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#0000ff" :background "#ffffff")
  (syntax-constant-attribute :foreground nil :background "#ffffff")
  (syntax-function-name-attribute :foreground nil :background "#ffffff")
  (syntax-variable-attribute :foreground nil :background "#ffffff")
  (syntax-type-attribute :foreground nil :background "#ffffff")
  (syntax-builtin-attribute :foreground nil :background "#ffffff"))
