(in-package :lem-user)

(define-color-theme "abap" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#F00" :background "#ffffff")
  (syntax-string-attribute :foreground "#5a2" :background "#ffffff")
  (syntax-comment-attribute :foreground "#888" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#00f" :background "#ffffff")
  (syntax-constant-attribute :foreground nil :background "#ffffff")
  (syntax-function-name-attribute :foreground nil :background "#ffffff")
  (syntax-variable-attribute :foreground nil :background "#ffffff")
  (syntax-type-attribute :foreground nil :background "#ffffff")
  (syntax-builtin-attribute :foreground nil :background "#ffffff"))
