(in-package :lem-user)

(define-color-theme "algol" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground nil)
  (syntax-string-attribute :foreground "#666")
  (syntax-comment-attribute :foreground "#888")
  (syntax-keyword-attribute :foreground nil)
  (syntax-constant-attribute :foreground "#666")
  (syntax-function-name-attribute :foreground "#666")
  (syntax-variable-attribute :foreground "#666")
  (syntax-type-attribute :foreground nil)
  (syntax-builtin-attribute :foreground nil))
