(in-package :lem-user)

(define-color-theme "arduino" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#a61717")
  (syntax-string-attribute :foreground "#7F8C8D")
  (syntax-comment-attribute :foreground "#95a5a6")
  (syntax-keyword-attribute :foreground "#728E00")
  (syntax-constant-attribute :foreground nil)
  (syntax-function-name-attribute :foreground "#D35400")
  (syntax-variable-attribute :foreground nil)
  (syntax-type-attribute :foreground "#00979D")
  (syntax-builtin-attribute :foreground "#728E00"))
