(in-package :lem-user)

(define-color-theme "arduino" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#a61717" :background "#ffffff")
  (syntax-string-attribute :foreground "#7F8C8D" :background "#ffffff")
  (syntax-comment-attribute :foreground "#95a5a6" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#728E00" :background "#ffffff")
  (syntax-constant-attribute :foreground nil :background "#ffffff")
  (syntax-function-name-attribute :foreground "#D35400" :background "#ffffff")
  (syntax-variable-attribute :foreground nil :background "#ffffff")
  (syntax-type-attribute :foreground "#00979D" :background "#ffffff")
  (syntax-builtin-attribute :foreground "#728E00" :background "#ffffff"))
