(in-package :lem-user)

(define-color-theme "autumn" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#F00" :background "#ffffff")
  (syntax-string-attribute :foreground "#aa5500" :background "#ffffff")
  (syntax-comment-attribute :foreground "#aaaaaa" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#0000aa" :background "#ffffff")
  (syntax-constant-attribute :foreground "#aa0000" :background "#ffffff")
  (syntax-function-name-attribute :foreground "#00aa00" :background "#ffffff")
  (syntax-variable-attribute :foreground "#aa0000" :background "#ffffff")
  (syntax-type-attribute :foreground "#00aaaa" :background "#ffffff")
  (syntax-builtin-attribute :foreground "#00aaaa" :background "#ffffff"))
