(in-package :lem-user)

(define-color-theme "autumn" ()
  (foreground "#000000")
  (background "#ffffff")
  (cursor :foreground "#ffffff" :background "#000000")
  (syntax-warning-attribute :foreground "#ff0000" :background "#ffffff")
  (syntax-string-attribute :foreground "#af5f00" :background "#ffffff")
  (syntax-comment-attribute :foreground "#a8a8a8" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#0000af" :background "#ffffff")
  (syntax-constant-attribute :foreground "#af0000" :background "#ffffff")
  (syntax-function-name-attribute :foreground "#00af00" :background "#ffffff")
  (syntax-variable-attribute :foreground "#af0000" :background "#ffffff")
  (syntax-type-attribute :foreground "#00afaf" :background "#ffffff")
  (syntax-builtin-attribute :foreground "#00afaf" :background "#ffffff"))
