(in-package :lem-user)

(define-color-theme "autumn" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#F00")
  (syntax-string-attribute :foreground "#aa5500")
  (syntax-comment-attribute :foreground "#aaaaaa")
  (syntax-keyword-attribute :foreground "#0000aa")
  (syntax-constant-attribute :foreground "#aa0000")
  (syntax-function-name-attribute :foreground "#00aa00")
  (syntax-variable-attribute :foreground "#aa0000")
  (syntax-type-attribute :foreground "#00aaaa")
  (syntax-builtin-attribute :foreground "#00aaaa"))
