(in-package :lem-user)

(define-color-theme "borland" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#a61717" :background "#ffffff")
  (syntax-string-attribute :foreground "#0000FF" :background "#ffffff")
  (syntax-comment-attribute :foreground "#008800" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#000080" :background "#ffffff")
  (syntax-constant-attribute :foreground nil :background "#ffffff")
  (syntax-function-name-attribute :foreground nil :background "#ffffff")
  (syntax-variable-attribute :foreground nil :background "#ffffff")
  (syntax-type-attribute :foreground nil :background "#ffffff")
  (syntax-builtin-attribute :foreground nil :background "#ffffff"))
