(in-package :lem-user)

(define-color-theme "colorful" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#F00")
  (syntax-string-attribute :foreground nil)
  (syntax-comment-attribute :foreground "#888")
  (syntax-keyword-attribute :foreground "#080")
  (syntax-constant-attribute :foreground "#036")
  (syntax-function-name-attribute :foreground "#06B")
  (syntax-variable-attribute :foreground "#963")
  (syntax-type-attribute :foreground "#339")
  (syntax-builtin-attribute :foreground "#007020"))
