(in-package :lem-user)

(define-color-theme "colorful" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#F00" :background "#ffffff")
  (syntax-string-attribute :foreground nil :background "#ffffff")
  (syntax-comment-attribute :foreground "#888" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#080" :background "#ffffff")
  (syntax-constant-attribute :foreground "#036" :background "#ffffff")
  (syntax-function-name-attribute :foreground "#06B" :background "#ffffff")
  (syntax-variable-attribute :foreground "#963" :background "#ffffff")
  (syntax-type-attribute :foreground "#339" :background "#ffffff")
  (syntax-builtin-attribute :foreground "#007020" :background "#ffffff"))
