(in-package :lem-user)

(define-color-theme "default" ()
  (foreground "#000000")
  (background "#f8f8f8")
  (syntax-warning-attribute :foreground nil)
  (syntax-string-attribute :foreground "#BA2121")
  (syntax-comment-attribute :foreground "#408080")
  (syntax-keyword-attribute :foreground "#008000")
  (syntax-constant-attribute :foreground "#880000")
  (syntax-function-name-attribute :foreground "#0000FF")
  (syntax-variable-attribute :foreground "#19177C")
  (syntax-type-attribute :foreground "#B00040")
  (syntax-builtin-attribute :foreground "#008000"))
