(in-package :lem-user)

(define-color-theme "emacs" ()
  (foreground "#000000")
  (background "#f8f8f8")
  (syntax-warning-attribute :foreground nil :background "#f8f8f8")
  (syntax-string-attribute :foreground "#BB4444" :background "#f8f8f8")
  (syntax-comment-attribute :foreground "#008800" :background "#f8f8f8")
  (syntax-keyword-attribute :foreground "#AA22FF" :background "#f8f8f8")
  (syntax-constant-attribute :foreground "#880000" :background "#f8f8f8")
  (syntax-function-name-attribute :foreground "#00A000" :background "#f8f8f8")
  (syntax-variable-attribute :foreground "#B8860B" :background "#f8f8f8")
  (syntax-type-attribute :foreground "#00BB00" :background "#f8f8f8")
  (syntax-builtin-attribute :foreground "#AA22FF" :background "#f8f8f8"))
