(in-package :lem-user)

(define-color-theme "emacs" ()
  (foreground "#000000")
  (background "#ffffff")
  (cursor :foreground "#ffffff" :background "#000000")
  (syntax-warning-attribute :foreground nil :background "#ffffff")
  (syntax-string-attribute :foreground "#af5f5f" :background "#ffffff")
  (syntax-comment-attribute :foreground "#008700" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#af00ff" :background "#ffffff")
  (syntax-constant-attribute :foreground "#870000" :background "#ffffff")
  (syntax-function-name-attribute :foreground "#00af00" :background "#ffffff")
  (syntax-variable-attribute :foreground "#af8700" :background "#ffffff")
  (syntax-type-attribute :foreground "#00af00" :background "#ffffff")
  (syntax-builtin-attribute :foreground "#af00ff" :background "#ffffff"))
