(in-package :lem-user)

(define-color-theme "friendly" ()
  (foreground "#000000")
  (background "#f0f0f0")
  (syntax-warning-attribute :foreground nil :background "#f0f0f0")
  (syntax-string-attribute :foreground "#4070a0" :background "#f0f0f0")
  (syntax-comment-attribute :foreground "#60a0b0" :background "#f0f0f0")
  (syntax-keyword-attribute :foreground "#007020" :background "#f0f0f0")
  (syntax-constant-attribute :foreground "#60add5" :background "#f0f0f0")
  (syntax-function-name-attribute :foreground "#06287e" :background "#f0f0f0")
  (syntax-variable-attribute :foreground "#bb60d5" :background "#f0f0f0")
  (syntax-type-attribute :foreground "#902000" :background "#f0f0f0")
  (syntax-builtin-attribute :foreground "#007020" :background "#f0f0f0"))
