(in-package :lem-user)

(define-color-theme "friendly" ()
  (foreground "#000000")
  (background "#f0f0f0")
  (syntax-warning-attribute :foreground nil)
  (syntax-string-attribute :foreground "#4070a0")
  (syntax-comment-attribute :foreground "#60a0b0")
  (syntax-keyword-attribute :foreground "#007020")
  (syntax-constant-attribute :foreground "#60add5")
  (syntax-function-name-attribute :foreground "#06287e")
  (syntax-variable-attribute :foreground "#bb60d5")
  (syntax-type-attribute :foreground "#902000")
  (syntax-builtin-attribute :foreground "#007020"))
