(in-package :lem-user)

(define-color-theme "fruity" ()
  (foreground "#ffffff")
  (background "#111111")
  (syntax-warning-attribute :foreground nil)
  (syntax-string-attribute :foreground "#0086d2")
  (syntax-comment-attribute :foreground "#008800")
  (syntax-keyword-attribute :foreground "#fb660a")
  (syntax-constant-attribute :foreground "#0086d2")
  (syntax-function-name-attribute :foreground "#ff0086")
  (syntax-variable-attribute :foreground "#fb660a")
  (syntax-type-attribute :foreground "#cdcaa9")
  (syntax-builtin-attribute :foreground nil))
