(in-package :lem-user)

(define-color-theme "igor" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground nil)
  (syntax-string-attribute :foreground "#009C00")
  (syntax-comment-attribute :foreground "#FF0000")
  (syntax-keyword-attribute :foreground "#0000FF")
  (syntax-constant-attribute :foreground nil)
  (syntax-function-name-attribute :foreground "#C34E00")
  (syntax-variable-attribute :foreground nil)
  (syntax-type-attribute :foreground nil)
  (syntax-builtin-attribute :foreground nil))
