(in-package :lem-user)

(define-color-theme "igor" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground nil :background "#ffffff")
  (syntax-string-attribute :foreground "#009C00" :background "#ffffff")
  (syntax-comment-attribute :foreground "#FF0000" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#0000FF" :background "#ffffff")
  (syntax-constant-attribute :foreground nil :background "#ffffff")
  (syntax-function-name-attribute :foreground "#C34E00" :background "#ffffff")
  (syntax-variable-attribute :foreground nil :background "#ffffff")
  (syntax-type-attribute :foreground nil :background "#ffffff")
  (syntax-builtin-attribute :foreground nil :background "#ffffff"))
