(in-package :lem-user)

(define-color-theme "lovelace" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground nil :background "#ffffff")
  (syntax-string-attribute :foreground "#b83838" :background "#ffffff")
  (syntax-comment-attribute :foreground "#888888" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#2838b0" :background "#ffffff")
  (syntax-constant-attribute :foreground "#b85820" :background "#ffffff")
  (syntax-function-name-attribute :foreground "#785840" :background "#ffffff")
  (syntax-variable-attribute :foreground "#b04040" :background "#ffffff")
  (syntax-type-attribute :foreground nil :background "#ffffff")
  (syntax-builtin-attribute :foreground "#388038" :background "#ffffff"))
