(in-package :lem-user)

(define-color-theme "lovelace" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground nil)
  (syntax-string-attribute :foreground "#b83838")
  (syntax-comment-attribute :foreground "#888888")
  (syntax-keyword-attribute :foreground "#2838b0")
  (syntax-constant-attribute :foreground "#b85820")
  (syntax-function-name-attribute :foreground "#785840")
  (syntax-variable-attribute :foreground "#b04040")
  (syntax-type-attribute :foreground nil)
  (syntax-builtin-attribute :foreground "#388038"))
