(in-package :lem-user)

(define-color-theme "manni" ()
  (foreground "#000000")
  (background "#eeeeee")
  (cursor :foreground "#eeeeee" :background "#000000")
  (syntax-warning-attribute :foreground "#af0000" :background "#eeeeee")
  (syntax-string-attribute :foreground "#d75f00" :background "#eeeeee")
  (syntax-comment-attribute :foreground "#0087ff" :background "#eeeeee")
  (syntax-keyword-attribute :foreground "#005f87" :background "#eeeeee")
  (syntax-constant-attribute :foreground "#5f5f00" :background "#eeeeee")
  (syntax-function-name-attribute :foreground "#d700ff" :background "#eeeeee")
  (syntax-variable-attribute :foreground "#262626" :background "#eeeeee")
  (syntax-type-attribute :foreground "#008080" :background "#eeeeee")
  (syntax-builtin-attribute :foreground "#585858" :background "#eeeeee"))
