(in-package :lem-user)

(define-color-theme "manni" ()
  (foreground "#000000")
  (background "#f0f3f3")
  (syntax-warning-attribute :foreground "#AA0000")
  (syntax-string-attribute :foreground "#CC3300")
  (syntax-comment-attribute :foreground "#0099FF")
  (syntax-keyword-attribute :foreground "#006699")
  (syntax-constant-attribute :foreground "#336600")
  (syntax-function-name-attribute :foreground "#CC00FF")
  (syntax-variable-attribute :foreground "#003333")
  (syntax-type-attribute :foreground "#007788")
  (syntax-builtin-attribute :foreground "#336666"))
