(in-package :lem-user)

(define-color-theme "murphy" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#F00" :background "#ffffff")
  (syntax-string-attribute :foreground nil :background "#ffffff")
  (syntax-comment-attribute :foreground "#666" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#289" :background "#ffffff")
  (syntax-constant-attribute :foreground "#5ed" :background "#ffffff")
  (syntax-function-name-attribute :foreground "#5ed" :background "#ffffff")
  (syntax-variable-attribute :foreground "#036" :background "#ffffff")
  (syntax-type-attribute :foreground "#66f" :background "#ffffff")
  (syntax-builtin-attribute :foreground "#072" :background "#ffffff"))
