(in-package :lem-user)

(define-color-theme "murphy" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#F00")
  (syntax-string-attribute :foreground nil)
  (syntax-comment-attribute :foreground "#666")
  (syntax-keyword-attribute :foreground "#289")
  (syntax-constant-attribute :foreground "#5ed")
  (syntax-function-name-attribute :foreground "#5ed")
  (syntax-variable-attribute :foreground "#036")
  (syntax-type-attribute :foreground "#66f")
  (syntax-builtin-attribute :foreground "#072"))
