(in-package :lem-user)

(define-color-theme "native" ()
  (foreground "#FFFFFF")
  (background "#1c1c1c")
  (cursor :foreground "#1c1c1c" :background "#FFFFFF")
  (syntax-warning-attribute :foreground "#af0000" :background "#1c1c1c")
  (syntax-string-attribute :foreground "#ffaf00" :background "#1c1c1c")
  (syntax-comment-attribute :foreground "#9e9e9e" :background "#1c1c1c")
  (syntax-keyword-attribute :foreground "#5faf00" :background "#1c1c1c")
  (syntax-constant-attribute :foreground "#5fffff" :background "#1c1c1c")
  (syntax-function-name-attribute :foreground "#5f87d7" :background "#1c1c1c")
  (syntax-variable-attribute :foreground "#5fffff" :background "#1c1c1c")
  (syntax-type-attribute :foreground nil :background "#1c1c1c")
  (syntax-builtin-attribute :foreground "#0087af" :background "#1c1c1c"))
