(in-package :lem-user)

(define-color-theme "native" ()
  (foreground "#ffffff")
  (background "#202020")
  (syntax-warning-attribute :foreground "#a61717")
  (syntax-string-attribute :foreground "#ed9d13")
  (syntax-comment-attribute :foreground "#999999")
  (syntax-keyword-attribute :foreground "#6ab825")
  (syntax-constant-attribute :foreground "#40ffff")
  (syntax-function-name-attribute :foreground "#447fcf")
  (syntax-variable-attribute :foreground "#40ffff")
  (syntax-type-attribute :foreground nil)
  (syntax-builtin-attribute :foreground "#24909d"))
