(in-package :lem-user)

(define-color-theme "paraiso-light" ()
  (foreground "#262626")
  (background "#e4e4e4")
  (syntax-warning-attribute :foreground "#ff5f5f" :background "#e4e4e4")
  (syntax-string-attribute :foreground "#5faf87" :background "#e4e4e4")
  (syntax-comment-attribute :foreground "#8a8a8a" :background "#e4e4e4")
  (syntax-keyword-attribute :foreground "#875faf" :background "#e4e4e4")
  (syntax-constant-attribute :foreground "#ff5f5f" :background "#e4e4e4")
  (syntax-function-name-attribute :foreground "#00afff" :background "#e4e4e4")
  (syntax-variable-attribute :foreground "#ff5f5f" :background "#e4e4e4")
  (syntax-type-attribute :foreground "#ffd700" :background "#e4e4e4")
  (syntax-builtin-attribute :foreground nil :background "#e4e4e4"))
