(in-package :lem-user)

(define-color-theme "paraiso-light" ()
  (foreground "#2f1e2e")
  (background "#e7e9db")
  (syntax-warning-attribute :foreground "#ef6155" :background "#e7e9db")
  (syntax-string-attribute :foreground "#48b685" :background "#e7e9db")
  (syntax-comment-attribute :foreground "#8d8687" :background "#e7e9db")
  (syntax-keyword-attribute :foreground "#815ba4" :background "#e7e9db")
  (syntax-constant-attribute :foreground "#ef6155" :background "#e7e9db")
  (syntax-function-name-attribute :foreground "#06b6ef" :background "#e7e9db")
  (syntax-variable-attribute :foreground "#ef6155" :background "#e7e9db")
  (syntax-type-attribute :foreground "#fec418" :background "#e7e9db")
  (syntax-builtin-attribute :foreground nil :background "#e7e9db"))
