(in-package :lem-user)

(define-color-theme "paraiso-dark" ()
  (foreground "#e7e9db")
  (background "#2f1e2e")
  (syntax-warning-attribute :foreground "#ef6155" :background "#2f1e2e")
  (syntax-string-attribute :foreground "#48b685" :background "#2f1e2e")
  (syntax-comment-attribute :foreground "#776e71" :background "#2f1e2e")
  (syntax-keyword-attribute :foreground "#815ba4" :background "#2f1e2e")
  (syntax-constant-attribute :foreground "#ef6155" :background "#2f1e2e")
  (syntax-function-name-attribute :foreground "#06b6ef" :background "#2f1e2e")
  (syntax-variable-attribute :foreground "#ef6155" :background "#2f1e2e")
  (syntax-type-attribute :foreground "#fec418" :background "#2f1e2e")
  (syntax-builtin-attribute :foreground nil :background "#2f1e2e"))
