(in-package :lem-user)

(define-color-theme "paraiso-light" ()
  (foreground "#2f1e2e")
  (background "#e7e9db")
  (syntax-warning-attribute :foreground "#ef6155")
  (syntax-string-attribute :foreground "#48b685")
  (syntax-comment-attribute :foreground "#8d8687")
  (syntax-keyword-attribute :foreground "#815ba4")
  (syntax-constant-attribute :foreground "#ef6155")
  (syntax-function-name-attribute :foreground "#06b6ef")
  (syntax-variable-attribute :foreground "#ef6155")
  (syntax-type-attribute :foreground "#fec418")
  (syntax-builtin-attribute :foreground nil))
