(in-package :lem-user)

(define-color-theme "pastie" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#a61717")
  (syntax-string-attribute :foreground "#dd2200")
  (syntax-comment-attribute :foreground "#888888")
  (syntax-keyword-attribute :foreground "#008800")
  (syntax-constant-attribute :foreground "#003366")
  (syntax-function-name-attribute :foreground "#0066bb")
  (syntax-variable-attribute :foreground "#336699")
  (syntax-type-attribute :foreground "#888888")
  (syntax-builtin-attribute :foreground "#003388"))
