(in-package :lem-user)

(define-color-theme "pastie" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#a61717" :background "#ffffff")
  (syntax-string-attribute :foreground "#dd2200" :background "#ffffff")
  (syntax-comment-attribute :foreground "#888888" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#008800" :background "#ffffff")
  (syntax-constant-attribute :foreground "#003366" :background "#ffffff")
  (syntax-function-name-attribute :foreground "#0066bb" :background "#ffffff")
  (syntax-variable-attribute :foreground "#336699" :background "#ffffff")
  (syntax-type-attribute :foreground "#888888" :background "#ffffff")
  (syntax-builtin-attribute :foreground "#003388" :background "#ffffff"))
