(in-package :lem-user)

(define-color-theme "perldoc" ()
  (foreground "#000000")
  (background "#eeeedd")
  (syntax-warning-attribute :foreground "#a61717")
  (syntax-string-attribute :foreground "#CD5555")
  (syntax-comment-attribute :foreground "#228B22")
  (syntax-keyword-attribute :foreground "#8B008B")
  (syntax-constant-attribute :foreground "#00688B")
  (syntax-function-name-attribute :foreground "#008b45")
  (syntax-variable-attribute :foreground "#00688B")
  (syntax-type-attribute :foreground "#00688B")
  (syntax-builtin-attribute :foreground "#658b00"))
