(in-package :lem-user)

(define-color-theme "perldoc" ()
  (foreground "#000000")
  (background "#eeeedd")
  (syntax-warning-attribute :foreground "#a61717" :background "#eeeedd")
  (syntax-string-attribute :foreground "#CD5555" :background "#eeeedd")
  (syntax-comment-attribute :foreground "#228B22" :background "#eeeedd")
  (syntax-keyword-attribute :foreground "#8B008B" :background "#eeeedd")
  (syntax-constant-attribute :foreground "#00688B" :background "#eeeedd")
  (syntax-function-name-attribute :foreground "#008b45" :background "#eeeedd")
  (syntax-variable-attribute :foreground "#00688B" :background "#eeeedd")
  (syntax-type-attribute :foreground "#00688B" :background "#eeeedd")
  (syntax-builtin-attribute :foreground "#658b00" :background "#eeeedd"))
