(in-package :lem-user)

(define-color-theme "rainbow_dash" ()
  (foreground "#4d4d4d")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#ffffff" :background "#ffffff")
  (syntax-string-attribute :foreground "#00cc66" :background "#ffffff")
  (syntax-comment-attribute :foreground "#0080ff" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#2c5dcd" :background "#ffffff")
  (syntax-constant-attribute :foreground "#318495" :background "#ffffff")
  (syntax-function-name-attribute :foreground "#ff8000" :background "#ffffff")
  (syntax-variable-attribute :foreground nil :background "#ffffff")
  (syntax-type-attribute :foreground "#5918bb" :background "#ffffff")
  (syntax-builtin-attribute :foreground "#5918bb" :background "#ffffff"))
