(in-package :lem-user)

(define-color-theme "rainbow_dash" ()
  (foreground "#4d4d4d")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#ffffff")
  (syntax-string-attribute :foreground "#00cc66")
  (syntax-comment-attribute :foreground "#0080ff")
  (syntax-keyword-attribute :foreground "#2c5dcd")
  (syntax-constant-attribute :foreground "#318495")
  (syntax-function-name-attribute :foreground "#ff8000")
  (syntax-variable-attribute :foreground nil)
  (syntax-type-attribute :foreground "#5918bb")
  (syntax-builtin-attribute :foreground "#5918bb"))
