(in-package :lem-user)

(define-color-theme "rrt" ()
  (foreground "#ffffff")
  (background "#000000")
  (syntax-warning-attribute :foreground nil)
  (syntax-string-attribute :foreground "#87ceeb")
  (syntax-comment-attribute :foreground "#00ff00")
  (syntax-keyword-attribute :foreground "#ff0000")
  (syntax-constant-attribute :foreground "#7fffd4")
  (syntax-function-name-attribute :foreground "#ffff00")
  (syntax-variable-attribute :foreground "#eedd82")
  (syntax-type-attribute :foreground "#ee82ee")
  (syntax-builtin-attribute :foreground nil))
