(in-package :lem-user)

(define-color-theme "tango" ()
  (foreground "#000000")
  (background "#ffffff")
  (cursor :foreground "#ffffff" :background "#000000")
  (syntax-warning-attribute :foreground "#af0000" :background "#ffffff")
  (syntax-string-attribute :foreground "#5f8700" :background "#ffffff")
  (syntax-comment-attribute :foreground "#875f00" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#005f87" :background "#ffffff")
  (syntax-constant-attribute :foreground "#000000" :background "#ffffff")
  (syntax-function-name-attribute :foreground "#000000" :background "#ffffff")
  (syntax-variable-attribute :foreground "#000000" :background "#ffffff")
  (syntax-type-attribute :foreground "#005f87" :background "#ffffff")
  (syntax-builtin-attribute :foreground "#005f87" :background "#ffffff"))
