(in-package :lem-user)

(define-color-theme "tango" ()
  (foreground "#000000")
  (background "#f8f8f8")
  (syntax-warning-attribute :foreground "#a40000")
  (syntax-string-attribute :foreground "#4e9a06")
  (syntax-comment-attribute :foreground "#8f5902")
  (syntax-keyword-attribute :foreground "#204a87")
  (syntax-constant-attribute :foreground "#000000")
  (syntax-function-name-attribute :foreground "#000000")
  (syntax-variable-attribute :foreground "#000000")
  (syntax-type-attribute :foreground "#204a87")
  (syntax-builtin-attribute :foreground "#204a87"))
