(in-package :lem-user)

(define-color-theme "trac" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#a61717")
  (syntax-string-attribute :foreground "#bb8844")
  (syntax-comment-attribute :foreground "#999988")
  (syntax-keyword-attribute :foreground nil)
  (syntax-constant-attribute :foreground "#008080")
  (syntax-function-name-attribute :foreground "#990000")
  (syntax-variable-attribute :foreground "#008080")
  (syntax-type-attribute :foreground "#445588")
  (syntax-builtin-attribute :foreground "#999999"))
