(in-package :lem-user)

(define-color-theme "trac" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#af0000" :background "#ffffff")
  (syntax-string-attribute :foreground "#af875f" :background "#ffffff")
  (syntax-comment-attribute :foreground "#949494" :background "#ffffff")
  (syntax-keyword-attribute :foreground nil :background "#ffffff")
  (syntax-constant-attribute :foreground "#008080" :background "#ffffff")
  (syntax-function-name-attribute :foreground "#870000" :background "#ffffff")
  (syntax-variable-attribute :foreground "#008080" :background "#ffffff")
  (syntax-type-attribute :foreground "#5f5f87" :background "#ffffff")
  (syntax-builtin-attribute :foreground "#9e9e9e" :background "#ffffff"))
