(in-package :lem-user)

(define-color-theme "trac" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#a61717" :background "#ffffff")
  (syntax-string-attribute :foreground "#bb8844" :background "#ffffff")
  (syntax-comment-attribute :foreground "#999988" :background "#ffffff")
  (syntax-keyword-attribute :foreground nil :background "#ffffff")
  (syntax-constant-attribute :foreground "#008080" :background "#ffffff")
  (syntax-function-name-attribute :foreground "#990000" :background "#ffffff")
  (syntax-variable-attribute :foreground "#008080" :background "#ffffff")
  (syntax-type-attribute :foreground "#445588" :background "#ffffff")
  (syntax-builtin-attribute :foreground "#999999" :background "#ffffff"))
