(in-package :lem-user)

(define-color-theme "vs" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground nil :background "#ffffff")
  (syntax-string-attribute :foreground "#a31515" :background "#ffffff")
  (syntax-comment-attribute :foreground "#008000" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#0000ff" :background "#ffffff")
  (syntax-constant-attribute :foreground nil :background "#ffffff")
  (syntax-function-name-attribute :foreground nil :background "#ffffff")
  (syntax-variable-attribute :foreground nil :background "#ffffff")
  (syntax-type-attribute :foreground "#2b91af" :background "#ffffff")
  (syntax-builtin-attribute :foreground nil :background "#ffffff"))
