(in-package :lem-user)

(define-color-theme "vs" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground nil)
  (syntax-string-attribute :foreground "#a31515")
  (syntax-comment-attribute :foreground "#008000")
  (syntax-keyword-attribute :foreground "#0000ff")
  (syntax-constant-attribute :foreground nil)
  (syntax-function-name-attribute :foreground nil)
  (syntax-variable-attribute :foreground nil)
  (syntax-type-attribute :foreground "#2b91af")
  (syntax-builtin-attribute :foreground nil))
