(in-package :lem-user)

(define-color-theme "xcode" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#000000" :background "#ffffff")
  (syntax-string-attribute :foreground "#d70000" :background "#ffffff")
  (syntax-comment-attribute :foreground "#008000" :background "#ffffff")
  (syntax-keyword-attribute :foreground "#af0087" :background "#ffffff")
  (syntax-constant-attribute :foreground nil :background "#ffffff")
  (syntax-function-name-attribute :foreground "#000000" :background "#ffffff")
  (syntax-variable-attribute :foreground "#000000" :background "#ffffff")
  (syntax-type-attribute :foreground nil :background "#ffffff")
  (syntax-builtin-attribute :foreground "#af0087" :background "#ffffff"))
