(in-package :lem-user)

(define-color-theme "xcode" ()
  (foreground "#000000")
  (background "#ffffff")
  (syntax-warning-attribute :foreground "#000000")
  (syntax-string-attribute :foreground "#C41A16")
  (syntax-comment-attribute :foreground "#177500")
  (syntax-keyword-attribute :foreground "#A90D91")
  (syntax-constant-attribute :foreground nil)
  (syntax-function-name-attribute :foreground "#000000")
  (syntax-variable-attribute :foreground "#000000")
  (syntax-type-attribute :foreground nil)
  (syntax-builtin-attribute :foreground "#A90D91"))
